# Generated by Django 2.1.4 on 2019-06-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_date', models.DateTimeField()),
                ('operation_id_1', models.CharField(max_length=15)),
                ('operation_id_2', models.CharField(max_length=15)),
                ('operation_id_3', models.CharField(max_length=15)),
                ('operation_id_4', models.CharField(max_length=15)),
                ('operation_id_5', models.CharField(max_length=15)),
                ('payment_type', models.CharField(max_length=64)),
                ('amount', models.FloatField()),
                ('t_hash', models.CharField(max_length=256)),
                ('main_balance', models.FloatField()),
                ('currency', models.CharField(max_length=8)),
                ('update_at', models.DateTimeField()),
            ],
        ),
    ]
